# Generated by Django 4.0.6 on 2022-08-25 16:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtagforum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eatforum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('snippet', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, default='', editable=False)),
                ('contents', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('edit_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hashtag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eatforum.hashtagforum')),
            ],
            options={
                'db_table': 'eatforum',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Commentforum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('eatforum', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eatforum.eatforum')),
            ],
        ),
    ]
