# Generated by Django 4.0.6 on 2022-08-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatforum', '0002_eatforum_likes_alter_eatforum_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatforum',
            name='likes',
        ),
    ]
