# Generated by Django 4.0.6 on 2022-08-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatforum', '0003_remove_eatforum_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryforum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='eatforum',
            name='category',
            field=models.ManyToManyField(to='eatforum.categoryforum'),
        ),
    ]
