# Generated by Django 4.0.6 on 2022-08-26 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatforum', '0004_categoryforum_eatforum_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatforum',
            name='author_name',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eatforum',
            name='snippet',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
