# Generated by Django 4.0.6 on 2022-09-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatforum', '0008_eatforum_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatforum',
            name='likes',
        ),
    ]
