# Generated by Django 4.0.6 on 2022-07-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Eatarticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('contents', models.TextField(default='')),
                ('slug', models.SlugField(blank=True, default='')),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('edit_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eatarticle.author')),
                ('hashtag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eatarticle.hashtag')),
            ],
            options={
                'db_table': 'eatarticle',
                'ordering': ['id'],
            },
        ),
    ]
