# Generated by Django 4.0.6 on 2022-07-25 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatarticle', '0003_eatarticle_likes_alter_eatarticle_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatarticle',
            name='likes',
        ),
        migrations.AddField(
            model_name='eatarticle',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
