# Generated by Django 4.0.6 on 2022-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatarticle', '0005_eatarticle_snippet_alter_eatarticle_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatarticle',
            name='snippet',
            field=models.CharField(default='內文詳情...', max_length=255),
        ),
    ]
