# Generated by Django 4.0.6 on 2022-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatarticle', '0006_alter_eatarticle_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatarticle',
            name='likes',
        ),
        migrations.AlterField(
            model_name='eatarticle',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Blog Post...', max_length=255),
        ),
    ]
