# Generated by Django 4.0.6 on 2022-07-29 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatarticle', '0007_remove_eatarticle_likes_alter_eatarticle_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatarticle',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Blog Post...', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author_name', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('eatarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eatarticle.eatarticle')),
            ],
        ),
    ]
