# Generated by Django 4.0.6 on 2022-07-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatarticle', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eatarticle',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='eatarticle',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eatarticle.eatarticle'),
        ),
    ]
