# Generated by Django 4.0.6 on 2022-07-29 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eatarticle', '0011_remove_eatarticle_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatarticle',
            name='author_name',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
